CREATE TABLE questions(
id INT,
category TEXT,
question TEXT,
A TEXT,B TEXT,C TEXT,D TEXT,
answer TEXT
);
INSERT INTO questions VALUES (1,'Road Signs','What does STOP sign mean?','Stop','Go','Speed','Park','A');
INSERT INTO questions VALUES (2,'Road Signs','Triangle sign indicates?','Warning','Order','Info','Speed','A');
INSERT INTO questions VALUES (3,'Road Signs','What does STOP sign mean?','Stop','Go','Speed','Park','A');
INSERT INTO questions VALUES (4,'Road Signs','Triangle sign indicates?','Warning','Order','Info','Speed','A');
INSERT INTO questions VALUES (5,'Road Signs','What does STOP sign mean?','Stop','Go','Speed','Park','A');
INSERT INTO questions VALUES (6,'Road Signs','Triangle sign indicates?','Warning','Order','Info','Speed','A');
INSERT INTO questions VALUES (7,'Road Signs','What does STOP sign mean?','Stop','Go','Speed','Park','A');
INSERT INTO questions VALUES (8,'Road Signs','Triangle sign indicates?','Warning','Order','Info','Speed','A');
INSERT INTO questions VALUES (9,'Road Signs','What does STOP sign mean?','Stop','Go','Speed','Park','A');
INSERT INTO questions VALUES (10,'Road Signs','Triangle sign indicates?','Warning','Order','Info','Speed','A');
INSERT INTO questions VALUES (11,'Road Signs','What does STOP sign mean?','Stop','Go','Speed','Park','A');
INSERT INTO questions VALUES (12,'Road Signs','Triangle sign indicates?','Warning','Order','Info','Speed','A');
INSERT INTO questions VALUES (13,'Road Signs','What does STOP sign mean?','Stop','Go','Speed','Park','A');
INSERT INTO questions VALUES (14,'Road Signs','Triangle sign indicates?','Warning','Order','Info','Speed','A');
INSERT INTO questions VALUES (15,'Road Signs','What does STOP sign mean?','Stop','Go','Speed','Park','A');
INSERT INTO questions VALUES (16,'Road Signs','Triangle sign indicates?','Warning','Order','Info','Speed','A');
INSERT INTO questions VALUES (17,'Road Signs','What does STOP sign mean?','Stop','Go','Speed','Park','A');
INSERT INTO questions VALUES (18,'Road Signs','Triangle sign indicates?','Warning','Order','Info','Speed','A');
INSERT INTO questions VALUES (19,'Road Signs','What does STOP sign mean?','Stop','Go','Speed','Park','A');
INSERT INTO questions VALUES (20,'Road Signs','Triangle sign indicates?','Warning','Order','Info','Speed','A');
INSERT INTO questions VALUES (21,'Road Signs','What does STOP sign mean?','Stop','Go','Speed','Park','A');
INSERT INTO questions VALUES (22,'Road Signs','Triangle sign indicates?','Warning','Order','Info','Speed','A');
INSERT INTO questions VALUES (23,'Road Signs','What does STOP sign mean?','Stop','Go','Speed','Park','A');
INSERT INTO questions VALUES (24,'Road Signs','Triangle sign indicates?','Warning','Order','Info','Speed','A');
INSERT INTO questions VALUES (25,'Road Signs','What does STOP sign mean?','Stop','Go','Speed','Park','A');
INSERT INTO questions VALUES (26,'Road Signs','Triangle sign indicates?','Warning','Order','Info','Speed','A');
INSERT INTO questions VALUES (27,'Road Signs','What does STOP sign mean?','Stop','Go','Speed','Park','A');
INSERT INTO questions VALUES (28,'Road Signs','Triangle sign indicates?','Warning','Order','Info','Speed','A');
INSERT INTO questions VALUES (29,'Road Signs','What does STOP sign mean?','Stop','Go','Speed','Park','A');
INSERT INTO questions VALUES (30,'Road Signs','Triangle sign indicates?','Warning','Order','Info','Speed','A');
INSERT INTO questions VALUES (31,'Road Signs','What does STOP sign mean?','Stop','Go','Speed','Park','A');
INSERT INTO questions VALUES (32,'Road Signs','Triangle sign indicates?','Warning','Order','Info','Speed','A');
INSERT INTO questions VALUES (33,'Road Signs','What does STOP sign mean?','Stop','Go','Speed','Park','A');
INSERT INTO questions VALUES (34,'Road Signs','Triangle sign indicates?','Warning','Order','Info','Speed','A');
INSERT INTO questions VALUES (35,'Road Signs','What does STOP sign mean?','Stop','Go','Speed','Park','A');
INSERT INTO questions VALUES (36,'Road Signs','Triangle sign indicates?','Warning','Order','Info','Speed','A');
INSERT INTO questions VALUES (37,'Road Signs','What does STOP sign mean?','Stop','Go','Speed','Park','A');
INSERT INTO questions VALUES (38,'Road Signs','Triangle sign indicates?','Warning','Order','Info','Speed','A');
INSERT INTO questions VALUES (39,'Road Signs','What does STOP sign mean?','Stop','Go','Speed','Park','A');
INSERT INTO questions VALUES (40,'Road Signs','Triangle sign indicates?','Warning','Order','Info','Speed','A');
INSERT INTO questions VALUES (41,'Road Signs','What does STOP sign mean?','Stop','Go','Speed','Park','A');
INSERT INTO questions VALUES (42,'Road Signs','Triangle sign indicates?','Warning','Order','Info','Speed','A');
INSERT INTO questions VALUES (43,'Road Signs','What does STOP sign mean?','Stop','Go','Speed','Park','A');
INSERT INTO questions VALUES (44,'Road Signs','Triangle sign indicates?','Warning','Order','Info','Speed','A');
INSERT INTO questions VALUES (45,'Road Signs','What does STOP sign mean?','Stop','Go','Speed','Park','A');
INSERT INTO questions VALUES (46,'Road Signs','Triangle sign indicates?','Warning','Order','Info','Speed','A');
INSERT INTO questions VALUES (47,'Road Signs','What does STOP sign mean?','Stop','Go','Speed','Park','A');
INSERT INTO questions VALUES (48,'Road Signs','Triangle sign indicates?','Warning','Order','Info','Speed','A');
INSERT INTO questions VALUES (49,'Road Signs','What does STOP sign mean?','Stop','Go','Speed','Park','A');
INSERT INTO questions VALUES (50,'Road Signs','Triangle sign indicates?','Warning','Order','Info','Speed','A');
INSERT INTO questions VALUES (51,'Road Signs','What does STOP sign mean?','Stop','Go','Speed','Park','A');
INSERT INTO questions VALUES (52,'Road Signs','Triangle sign indicates?','Warning','Order','Info','Speed','A');
INSERT INTO questions VALUES (53,'Road Signs','What does STOP sign mean?','Stop','Go','Speed','Park','A');
INSERT INTO questions VALUES (54,'Road Signs','Triangle sign indicates?','Warning','Order','Info','Speed','A');
INSERT INTO questions VALUES (55,'Road Signs','What does STOP sign mean?','Stop','Go','Speed','Park','A');
INSERT INTO questions VALUES (56,'Road Signs','Triangle sign indicates?','Warning','Order','Info','Speed','A');
INSERT INTO questions VALUES (57,'Road Signs','What does STOP sign mean?','Stop','Go','Speed','Park','A');
INSERT INTO questions VALUES (58,'Road Signs','Triangle sign indicates?','Warning','Order','Info','Speed','A');
INSERT INTO questions VALUES (59,'Road Signs','What does STOP sign mean?','Stop','Go','Speed','Park','A');
INSERT INTO questions VALUES (60,'Road Signs','Triangle sign indicates?','Warning','Order','Info','Speed','A');
INSERT INTO questions VALUES (61,'Road Signs','What does STOP sign mean?','Stop','Go','Speed','Park','A');
INSERT INTO questions VALUES (62,'Road Signs','Triangle sign indicates?','Warning','Order','Info','Speed','A');
INSERT INTO questions VALUES (63,'Road Signs','What does STOP sign mean?','Stop','Go','Speed','Park','A');
INSERT INTO questions VALUES (64,'Road Signs','Triangle sign indicates?','Warning','Order','Info','Speed','A');
INSERT INTO questions VALUES (65,'Road Signs','What does STOP sign mean?','Stop','Go','Speed','Park','A');
INSERT INTO questions VALUES (66,'Road Signs','Triangle sign indicates?','Warning','Order','Info','Speed','A');
INSERT INTO questions VALUES (67,'Road Signs','What does STOP sign mean?','Stop','Go','Speed','Park','A');
INSERT INTO questions VALUES (68,'Road Signs','Triangle sign indicates?','Warning','Order','Info','Speed','A');
INSERT INTO questions VALUES (69,'Road Signs','What does STOP sign mean?','Stop','Go','Speed','Park','A');
INSERT INTO questions VALUES (70,'Road Signs','Triangle sign indicates?','Warning','Order','Info','Speed','A');
INSERT INTO questions VALUES (71,'Traffic Rules','Seat belt is for?','Safety','Style','Speed','Noise','A');
INSERT INTO questions VALUES (72,'Traffic Rules','Phone use while driving?','Allowed','Illegal','Optional','None','B');
INSERT INTO questions VALUES (73,'Traffic Rules','Seat belt is for?','Safety','Style','Speed','Noise','A');
INSERT INTO questions VALUES (74,'Traffic Rules','Phone use while driving?','Allowed','Illegal','Optional','None','B');
INSERT INTO questions VALUES (75,'Traffic Rules','Seat belt is for?','Safety','Style','Speed','Noise','A');
INSERT INTO questions VALUES (76,'Traffic Rules','Phone use while driving?','Allowed','Illegal','Optional','None','B');
INSERT INTO questions VALUES (77,'Traffic Rules','Seat belt is for?','Safety','Style','Speed','Noise','A');
INSERT INTO questions VALUES (78,'Traffic Rules','Phone use while driving?','Allowed','Illegal','Optional','None','B');
INSERT INTO questions VALUES (79,'Traffic Rules','Seat belt is for?','Safety','Style','Speed','Noise','A');
INSERT INTO questions VALUES (80,'Traffic Rules','Phone use while driving?','Allowed','Illegal','Optional','None','B');
INSERT INTO questions VALUES (81,'Traffic Rules','Seat belt is for?','Safety','Style','Speed','Noise','A');
INSERT INTO questions VALUES (82,'Traffic Rules','Phone use while driving?','Allowed','Illegal','Optional','None','B');
INSERT INTO questions VALUES (83,'Traffic Rules','Seat belt is for?','Safety','Style','Speed','Noise','A');
INSERT INTO questions VALUES (84,'Traffic Rules','Phone use while driving?','Allowed','Illegal','Optional','None','B');
INSERT INTO questions VALUES (85,'Traffic Rules','Seat belt is for?','Safety','Style','Speed','Noise','A');
INSERT INTO questions VALUES (86,'Traffic Rules','Phone use while driving?','Allowed','Illegal','Optional','None','B');
INSERT INTO questions VALUES (87,'Traffic Rules','Seat belt is for?','Safety','Style','Speed','Noise','A');
INSERT INTO questions VALUES (88,'Traffic Rules','Phone use while driving?','Allowed','Illegal','Optional','None','B');
INSERT INTO questions VALUES (89,'Traffic Rules','Seat belt is for?','Safety','Style','Speed','Noise','A');
INSERT INTO questions VALUES (90,'Traffic Rules','Phone use while driving?','Allowed','Illegal','Optional','None','B');
INSERT INTO questions VALUES (91,'Traffic Rules','Seat belt is for?','Safety','Style','Speed','Noise','A');
INSERT INTO questions VALUES (92,'Traffic Rules','Phone use while driving?','Allowed','Illegal','Optional','None','B');
INSERT INTO questions VALUES (93,'Traffic Rules','Seat belt is for?','Safety','Style','Speed','Noise','A');
INSERT INTO questions VALUES (94,'Traffic Rules','Phone use while driving?','Allowed','Illegal','Optional','None','B');
INSERT INTO questions VALUES (95,'Traffic Rules','Seat belt is for?','Safety','Style','Speed','Noise','A');
INSERT INTO questions VALUES (96,'Traffic Rules','Phone use while driving?','Allowed','Illegal','Optional','None','B');
INSERT INTO questions VALUES (97,'Traffic Rules','Seat belt is for?','Safety','Style','Speed','Noise','A');
INSERT INTO questions VALUES (98,'Traffic Rules','Phone use while driving?','Allowed','Illegal','Optional','None','B');
INSERT INTO questions VALUES (99,'Traffic Rules','Seat belt is for?','Safety','Style','Speed','Noise','A');
INSERT INTO questions VALUES (100,'Traffic Rules','Phone use while driving?','Allowed','Illegal','Optional','None','B');
INSERT INTO questions VALUES (101,'Traffic Rules','Seat belt is for?','Safety','Style','Speed','Noise','A');
INSERT INTO questions VALUES (102,'Traffic Rules','Phone use while driving?','Allowed','Illegal','Optional','None','B');
INSERT INTO questions VALUES (103,'Traffic Rules','Seat belt is for?','Safety','Style','Speed','Noise','A');
INSERT INTO questions VALUES (104,'Traffic Rules','Phone use while driving?','Allowed','Illegal','Optional','None','B');
INSERT INTO questions VALUES (105,'Traffic Rules','Seat belt is for?','Safety','Style','Speed','Noise','A');
INSERT INTO questions VALUES (106,'Traffic Rules','Phone use while driving?','Allowed','Illegal','Optional','None','B');
INSERT INTO questions VALUES (107,'Traffic Rules','Seat belt is for?','Safety','Style','Speed','Noise','A');
INSERT INTO questions VALUES (108,'Traffic Rules','Phone use while driving?','Allowed','Illegal','Optional','None','B');
INSERT INTO questions VALUES (109,'Traffic Rules','Seat belt is for?','Safety','Style','Speed','Noise','A');
INSERT INTO questions VALUES (110,'Traffic Rules','Phone use while driving?','Allowed','Illegal','Optional','None','B');
INSERT INTO questions VALUES (111,'Traffic Rules','Seat belt is for?','Safety','Style','Speed','Noise','A');
INSERT INTO questions VALUES (112,'Traffic Rules','Phone use while driving?','Allowed','Illegal','Optional','None','B');
INSERT INTO questions VALUES (113,'Traffic Rules','Seat belt is for?','Safety','Style','Speed','Noise','A');
INSERT INTO questions VALUES (114,'Traffic Rules','Phone use while driving?','Allowed','Illegal','Optional','None','B');
INSERT INTO questions VALUES (115,'Traffic Rules','Seat belt is for?','Safety','Style','Speed','Noise','A');
INSERT INTO questions VALUES (116,'Traffic Rules','Phone use while driving?','Allowed','Illegal','Optional','None','B');
INSERT INTO questions VALUES (117,'Traffic Rules','Seat belt is for?','Safety','Style','Speed','Noise','A');
INSERT INTO questions VALUES (118,'Traffic Rules','Phone use while driving?','Allowed','Illegal','Optional','None','B');
INSERT INTO questions VALUES (119,'Traffic Rules','Seat belt is for?','Safety','Style','Speed','Noise','A');
INSERT INTO questions VALUES (120,'Traffic Rules','Phone use while driving?','Allowed','Illegal','Optional','None','B');
INSERT INTO questions VALUES (121,'Traffic Rules','Seat belt is for?','Safety','Style','Speed','Noise','A');
INSERT INTO questions VALUES (122,'Traffic Rules','Phone use while driving?','Allowed','Illegal','Optional','None','B');
INSERT INTO questions VALUES (123,'Traffic Rules','Seat belt is for?','Safety','Style','Speed','Noise','A');
INSERT INTO questions VALUES (124,'Traffic Rules','Phone use while driving?','Allowed','Illegal','Optional','None','B');
INSERT INTO questions VALUES (125,'Traffic Rules','Seat belt is for?','Safety','Style','Speed','Noise','A');
INSERT INTO questions VALUES (126,'Traffic Rules','Phone use while driving?','Allowed','Illegal','Optional','None','B');
INSERT INTO questions VALUES (127,'Traffic Rules','Seat belt is for?','Safety','Style','Speed','Noise','A');
INSERT INTO questions VALUES (128,'Traffic Rules','Phone use while driving?','Allowed','Illegal','Optional','None','B');
INSERT INTO questions VALUES (129,'Traffic Rules','Seat belt is for?','Safety','Style','Speed','Noise','A');
INSERT INTO questions VALUES (130,'Traffic Rules','Phone use while driving?','Allowed','Illegal','Optional','None','B');
INSERT INTO questions VALUES (131,'Traffic Rules','Seat belt is for?','Safety','Style','Speed','Noise','A');
INSERT INTO questions VALUES (132,'Traffic Rules','Phone use while driving?','Allowed','Illegal','Optional','None','B');
INSERT INTO questions VALUES (133,'Traffic Rules','Seat belt is for?','Safety','Style','Speed','Noise','A');
INSERT INTO questions VALUES (134,'Traffic Rules','Phone use while driving?','Allowed','Illegal','Optional','None','B');
INSERT INTO questions VALUES (135,'Traffic Rules','Seat belt is for?','Safety','Style','Speed','Noise','A');
INSERT INTO questions VALUES (136,'Traffic Rules','Phone use while driving?','Allowed','Illegal','Optional','None','B');
INSERT INTO questions VALUES (137,'Traffic Rules','Seat belt is for?','Safety','Style','Speed','Noise','A');
INSERT INTO questions VALUES (138,'Traffic Rules','Phone use while driving?','Allowed','Illegal','Optional','None','B');
INSERT INTO questions VALUES (139,'Traffic Rules','Seat belt is for?','Safety','Style','Speed','Noise','A');
INSERT INTO questions VALUES (140,'Traffic Rules','Phone use while driving?','Allowed','Illegal','Optional','None','B');
INSERT INTO questions VALUES (141,'Defensive Driving','Safe distance?','1 sec','2 sec','5 sec','None','B');
INSERT INTO questions VALUES (142,'Defensive Driving','Safe distance?','1 sec','2 sec','5 sec','None','B');
INSERT INTO questions VALUES (143,'Defensive Driving','Safe distance?','1 sec','2 sec','5 sec','None','B');
INSERT INTO questions VALUES (144,'Defensive Driving','Safe distance?','1 sec','2 sec','5 sec','None','B');
INSERT INTO questions VALUES (145,'Defensive Driving','Safe distance?','1 sec','2 sec','5 sec','None','B');
INSERT INTO questions VALUES (146,'Defensive Driving','Safe distance?','1 sec','2 sec','5 sec','None','B');
INSERT INTO questions VALUES (147,'Defensive Driving','Safe distance?','1 sec','2 sec','5 sec','None','B');
INSERT INTO questions VALUES (148,'Defensive Driving','Safe distance?','1 sec','2 sec','5 sec','None','B');
INSERT INTO questions VALUES (149,'Defensive Driving','Safe distance?','1 sec','2 sec','5 sec','None','B');
INSERT INTO questions VALUES (150,'Defensive Driving','Safe distance?','1 sec','2 sec','5 sec','None','B');
INSERT INTO questions VALUES (151,'Defensive Driving','Safe distance?','1 sec','2 sec','5 sec','None','B');
INSERT INTO questions VALUES (152,'Defensive Driving','Safe distance?','1 sec','2 sec','5 sec','None','B');
INSERT INTO questions VALUES (153,'Defensive Driving','Safe distance?','1 sec','2 sec','5 sec','None','B');
INSERT INTO questions VALUES (154,'Defensive Driving','Safe distance?','1 sec','2 sec','5 sec','None','B');
INSERT INTO questions VALUES (155,'Defensive Driving','Safe distance?','1 sec','2 sec','5 sec','None','B');
INSERT INTO questions VALUES (156,'Defensive Driving','Safe distance?','1 sec','2 sec','5 sec','None','B');
INSERT INTO questions VALUES (157,'Defensive Driving','Safe distance?','1 sec','2 sec','5 sec','None','B');
INSERT INTO questions VALUES (158,'Defensive Driving','Safe distance?','1 sec','2 sec','5 sec','None','B');
INSERT INTO questions VALUES (159,'Defensive Driving','Safe distance?','1 sec','2 sec','5 sec','None','B');
INSERT INTO questions VALUES (160,'Defensive Driving','Safe distance?','1 sec','2 sec','5 sec','None','B');
INSERT INTO questions VALUES (161,'Defensive Driving','Safe distance?','1 sec','2 sec','5 sec','None','B');
INSERT INTO questions VALUES (162,'Defensive Driving','Safe distance?','1 sec','2 sec','5 sec','None','B');
INSERT INTO questions VALUES (163,'Defensive Driving','Safe distance?','1 sec','2 sec','5 sec','None','B');
INSERT INTO questions VALUES (164,'Defensive Driving','Safe distance?','1 sec','2 sec','5 sec','None','B');
INSERT INTO questions VALUES (165,'Defensive Driving','Safe distance?','1 sec','2 sec','5 sec','None','B');
INSERT INTO questions VALUES (166,'Defensive Driving','Safe distance?','1 sec','2 sec','5 sec','None','B');
INSERT INTO questions VALUES (167,'Defensive Driving','Safe distance?','1 sec','2 sec','5 sec','None','B');
INSERT INTO questions VALUES (168,'Defensive Driving','Safe distance?','1 sec','2 sec','5 sec','None','B');
INSERT INTO questions VALUES (169,'Defensive Driving','Safe distance?','1 sec','2 sec','5 sec','None','B');
INSERT INTO questions VALUES (170,'Defensive Driving','Safe distance?','1 sec','2 sec','5 sec','None','B');
INSERT INTO questions VALUES (171,'Defensive Driving','Safe distance?','1 sec','2 sec','5 sec','None','B');
INSERT INTO questions VALUES (172,'Defensive Driving','Safe distance?','1 sec','2 sec','5 sec','None','B');
INSERT INTO questions VALUES (173,'Defensive Driving','Safe distance?','1 sec','2 sec','5 sec','None','B');
INSERT INTO questions VALUES (174,'Defensive Driving','Safe distance?','1 sec','2 sec','5 sec','None','B');
INSERT INTO questions VALUES (175,'Defensive Driving','Safe distance?','1 sec','2 sec','5 sec','None','B');
INSERT INTO questions VALUES (176,'Defensive Driving','Safe distance?','1 sec','2 sec','5 sec','None','B');
INSERT INTO questions VALUES (177,'Defensive Driving','Safe distance?','1 sec','2 sec','5 sec','None','B');
INSERT INTO questions VALUES (178,'Defensive Driving','Safe distance?','1 sec','2 sec','5 sec','None','B');
INSERT INTO questions VALUES (179,'Defensive Driving','Safe distance?','1 sec','2 sec','5 sec','None','B');
INSERT INTO questions VALUES (180,'Defensive Driving','Safe distance?','1 sec','2 sec','5 sec','None','B');
INSERT INTO questions VALUES (181,'Defensive Driving','Safe distance?','1 sec','2 sec','5 sec','None','B');
INSERT INTO questions VALUES (182,'Defensive Driving','Safe distance?','1 sec','2 sec','5 sec','None','B');
INSERT INTO questions VALUES (183,'Defensive Driving','Safe distance?','1 sec','2 sec','5 sec','None','B');
INSERT INTO questions VALUES (184,'Defensive Driving','Safe distance?','1 sec','2 sec','5 sec','None','B');
INSERT INTO questions VALUES (185,'Defensive Driving','Safe distance?','1 sec','2 sec','5 sec','None','B');
INSERT INTO questions VALUES (186,'Defensive Driving','Safe distance?','1 sec','2 sec','5 sec','None','B');
INSERT INTO questions VALUES (187,'Defensive Driving','Safe distance?','1 sec','2 sec','5 sec','None','B');
INSERT INTO questions VALUES (188,'Defensive Driving','Safe distance?','1 sec','2 sec','5 sec','None','B');
INSERT INTO questions VALUES (189,'Defensive Driving','Safe distance?','1 sec','2 sec','5 sec','None','B');
INSERT INTO questions VALUES (190,'Defensive Driving','Safe distance?','1 sec','2 sec','5 sec','None','B');
INSERT INTO questions VALUES (191,'Vehicle Mechanics','Engine oil used for?','Lubrication','Painting','Cooling only','Fuel','A');
INSERT INTO questions VALUES (192,'Vehicle Mechanics','Engine oil used for?','Lubrication','Painting','Cooling only','Fuel','A');
INSERT INTO questions VALUES (193,'Vehicle Mechanics','Engine oil used for?','Lubrication','Painting','Cooling only','Fuel','A');
INSERT INTO questions VALUES (194,'Vehicle Mechanics','Engine oil used for?','Lubrication','Painting','Cooling only','Fuel','A');
INSERT INTO questions VALUES (195,'Vehicle Mechanics','Engine oil used for?','Lubrication','Painting','Cooling only','Fuel','A');
INSERT INTO questions VALUES (196,'Vehicle Mechanics','Engine oil used for?','Lubrication','Painting','Cooling only','Fuel','A');
INSERT INTO questions VALUES (197,'Vehicle Mechanics','Engine oil used for?','Lubrication','Painting','Cooling only','Fuel','A');
INSERT INTO questions VALUES (198,'Vehicle Mechanics','Engine oil used for?','Lubrication','Painting','Cooling only','Fuel','A');
INSERT INTO questions VALUES (199,'Vehicle Mechanics','Engine oil used for?','Lubrication','Painting','Cooling only','Fuel','A');
INSERT INTO questions VALUES (200,'Vehicle Mechanics','Engine oil used for?','Lubrication','Painting','Cooling only','Fuel','A');
INSERT INTO questions VALUES (201,'Vehicle Mechanics','Engine oil used for?','Lubrication','Painting','Cooling only','Fuel','A');
INSERT INTO questions VALUES (202,'Vehicle Mechanics','Engine oil used for?','Lubrication','Painting','Cooling only','Fuel','A');
INSERT INTO questions VALUES (203,'Vehicle Mechanics','Engine oil used for?','Lubrication','Painting','Cooling only','Fuel','A');
INSERT INTO questions VALUES (204,'Vehicle Mechanics','Engine oil used for?','Lubrication','Painting','Cooling only','Fuel','A');
INSERT INTO questions VALUES (205,'Vehicle Mechanics','Engine oil used for?','Lubrication','Painting','Cooling only','Fuel','A');
INSERT INTO questions VALUES (206,'Vehicle Mechanics','Engine oil used for?','Lubrication','Painting','Cooling only','Fuel','A');
INSERT INTO questions VALUES (207,'Vehicle Mechanics','Engine oil used for?','Lubrication','Painting','Cooling only','Fuel','A');
INSERT INTO questions VALUES (208,'Vehicle Mechanics','Engine oil used for?','Lubrication','Painting','Cooling only','Fuel','A');
INSERT INTO questions VALUES (209,'Vehicle Mechanics','Engine oil used for?','Lubrication','Painting','Cooling only','Fuel','A');
INSERT INTO questions VALUES (210,'Vehicle Mechanics','Engine oil used for?','Lubrication','Painting','Cooling only','Fuel','A');
INSERT INTO questions VALUES (211,'Vehicle Mechanics','Engine oil used for?','Lubrication','Painting','Cooling only','Fuel','A');
INSERT INTO questions VALUES (212,'Vehicle Mechanics','Engine oil used for?','Lubrication','Painting','Cooling only','Fuel','A');
INSERT INTO questions VALUES (213,'Vehicle Mechanics','Engine oil used for?','Lubrication','Painting','Cooling only','Fuel','A');
INSERT INTO questions VALUES (214,'Vehicle Mechanics','Engine oil used for?','Lubrication','Painting','Cooling only','Fuel','A');
INSERT INTO questions VALUES (215,'Vehicle Mechanics','Engine oil used for?','Lubrication','Painting','Cooling only','Fuel','A');
INSERT INTO questions VALUES (216,'Vehicle Mechanics','Engine oil used for?','Lubrication','Painting','Cooling only','Fuel','A');
INSERT INTO questions VALUES (217,'Vehicle Mechanics','Engine oil used for?','Lubrication','Painting','Cooling only','Fuel','A');
INSERT INTO questions VALUES (218,'Vehicle Mechanics','Engine oil used for?','Lubrication','Painting','Cooling only','Fuel','A');
INSERT INTO questions VALUES (219,'Vehicle Mechanics','Engine oil used for?','Lubrication','Painting','Cooling only','Fuel','A');
INSERT INTO questions VALUES (220,'Vehicle Mechanics','Engine oil used for?','Lubrication','Painting','Cooling only','Fuel','A');
INSERT INTO questions VALUES (221,'Vehicle Mechanics','Engine oil used for?','Lubrication','Painting','Cooling only','Fuel','A');
INSERT INTO questions VALUES (222,'Vehicle Mechanics','Engine oil used for?','Lubrication','Painting','Cooling only','Fuel','A');
INSERT INTO questions VALUES (223,'Vehicle Mechanics','Engine oil used for?','Lubrication','Painting','Cooling only','Fuel','A');
INSERT INTO questions VALUES (224,'Vehicle Mechanics','Engine oil used for?','Lubrication','Painting','Cooling only','Fuel','A');
INSERT INTO questions VALUES (225,'Vehicle Mechanics','Engine oil used for?','Lubrication','Painting','Cooling only','Fuel','A');
INSERT INTO questions VALUES (226,'Vehicle Mechanics','Engine oil used for?','Lubrication','Painting','Cooling only','Fuel','A');
INSERT INTO questions VALUES (227,'Vehicle Mechanics','Engine oil used for?','Lubrication','Painting','Cooling only','Fuel','A');
INSERT INTO questions VALUES (228,'Vehicle Mechanics','Engine oil used for?','Lubrication','Painting','Cooling only','Fuel','A');
INSERT INTO questions VALUES (229,'Vehicle Mechanics','Engine oil used for?','Lubrication','Painting','Cooling only','Fuel','A');
INSERT INTO questions VALUES (230,'Vehicle Mechanics','Engine oil used for?','Lubrication','Painting','Cooling only','Fuel','A');
INSERT INTO questions VALUES (231,'Vehicle Mechanics','Engine oil used for?','Lubrication','Painting','Cooling only','Fuel','A');
INSERT INTO questions VALUES (232,'Vehicle Mechanics','Engine oil used for?','Lubrication','Painting','Cooling only','Fuel','A');
INSERT INTO questions VALUES (233,'Vehicle Mechanics','Engine oil used for?','Lubrication','Painting','Cooling only','Fuel','A');
INSERT INTO questions VALUES (234,'Vehicle Mechanics','Engine oil used for?','Lubrication','Painting','Cooling only','Fuel','A');
INSERT INTO questions VALUES (235,'Vehicle Mechanics','Engine oil used for?','Lubrication','Painting','Cooling only','Fuel','A');
INSERT INTO questions VALUES (236,'Vehicle Mechanics','Engine oil used for?','Lubrication','Painting','Cooling only','Fuel','A');
INSERT INTO questions VALUES (237,'Vehicle Mechanics','Engine oil used for?','Lubrication','Painting','Cooling only','Fuel','A');
INSERT INTO questions VALUES (238,'Vehicle Mechanics','Engine oil used for?','Lubrication','Painting','Cooling only','Fuel','A');
INSERT INTO questions VALUES (239,'Vehicle Mechanics','Engine oil used for?','Lubrication','Painting','Cooling only','Fuel','A');
INSERT INTO questions VALUES (240,'Vehicle Mechanics','Engine oil used for?','Lubrication','Painting','Cooling only','Fuel','A');
INSERT INTO questions VALUES (241,'Human Factors','Alcohol affects?','Reaction time','Car speed','Road','Tyres','A');
INSERT INTO questions VALUES (242,'Human Factors','Alcohol affects?','Reaction time','Car speed','Road','Tyres','A');
INSERT INTO questions VALUES (243,'Human Factors','Alcohol affects?','Reaction time','Car speed','Road','Tyres','A');
INSERT INTO questions VALUES (244,'Human Factors','Alcohol affects?','Reaction time','Car speed','Road','Tyres','A');
INSERT INTO questions VALUES (245,'Human Factors','Alcohol affects?','Reaction time','Car speed','Road','Tyres','A');
INSERT INTO questions VALUES (246,'Human Factors','Alcohol affects?','Reaction time','Car speed','Road','Tyres','A');
INSERT INTO questions VALUES (247,'Human Factors','Alcohol affects?','Reaction time','Car speed','Road','Tyres','A');
INSERT INTO questions VALUES (248,'Human Factors','Alcohol affects?','Reaction time','Car speed','Road','Tyres','A');
INSERT INTO questions VALUES (249,'Human Factors','Alcohol affects?','Reaction time','Car speed','Road','Tyres','A');
INSERT INTO questions VALUES (250,'Human Factors','Alcohol affects?','Reaction time','Car speed','Road','Tyres','A');
INSERT INTO questions VALUES (251,'Human Factors','Alcohol affects?','Reaction time','Car speed','Road','Tyres','A');
INSERT INTO questions VALUES (252,'Human Factors','Alcohol affects?','Reaction time','Car speed','Road','Tyres','A');
INSERT INTO questions VALUES (253,'Human Factors','Alcohol affects?','Reaction time','Car speed','Road','Tyres','A');
INSERT INTO questions VALUES (254,'Human Factors','Alcohol affects?','Reaction time','Car speed','Road','Tyres','A');
INSERT INTO questions VALUES (255,'Human Factors','Alcohol affects?','Reaction time','Car speed','Road','Tyres','A');
INSERT INTO questions VALUES (256,'Human Factors','Alcohol affects?','Reaction time','Car speed','Road','Tyres','A');
INSERT INTO questions VALUES (257,'Human Factors','Alcohol affects?','Reaction time','Car speed','Road','Tyres','A');
INSERT INTO questions VALUES (258,'Human Factors','Alcohol affects?','Reaction time','Car speed','Road','Tyres','A');
INSERT INTO questions VALUES (259,'Human Factors','Alcohol affects?','Reaction time','Car speed','Road','Tyres','A');
INSERT INTO questions VALUES (260,'Human Factors','Alcohol affects?','Reaction time','Car speed','Road','Tyres','A');
INSERT INTO questions VALUES (261,'Human Factors','Alcohol affects?','Reaction time','Car speed','Road','Tyres','A');
INSERT INTO questions VALUES (262,'Human Factors','Alcohol affects?','Reaction time','Car speed','Road','Tyres','A');
INSERT INTO questions VALUES (263,'Human Factors','Alcohol affects?','Reaction time','Car speed','Road','Tyres','A');
INSERT INTO questions VALUES (264,'Human Factors','Alcohol affects?','Reaction time','Car speed','Road','Tyres','A');
INSERT INTO questions VALUES (265,'Human Factors','Alcohol affects?','Reaction time','Car speed','Road','Tyres','A');
INSERT INTO questions VALUES (266,'Human Factors','Alcohol affects?','Reaction time','Car speed','Road','Tyres','A');
INSERT INTO questions VALUES (267,'Human Factors','Alcohol affects?','Reaction time','Car speed','Road','Tyres','A');
INSERT INTO questions VALUES (268,'Human Factors','Alcohol affects?','Reaction time','Car speed','Road','Tyres','A');
INSERT INTO questions VALUES (269,'Human Factors','Alcohol affects?','Reaction time','Car speed','Road','Tyres','A');
INSERT INTO questions VALUES (270,'Human Factors','Alcohol affects?','Reaction time','Car speed','Road','Tyres','A');
INSERT INTO questions VALUES (271,'Human Factors','Alcohol affects?','Reaction time','Car speed','Road','Tyres','A');
INSERT INTO questions VALUES (272,'Human Factors','Alcohol affects?','Reaction time','Car speed','Road','Tyres','A');
INSERT INTO questions VALUES (273,'Human Factors','Alcohol affects?','Reaction time','Car speed','Road','Tyres','A');
INSERT INTO questions VALUES (274,'Human Factors','Alcohol affects?','Reaction time','Car speed','Road','Tyres','A');
INSERT INTO questions VALUES (275,'Human Factors','Alcohol affects?','Reaction time','Car speed','Road','Tyres','A');
INSERT INTO questions VALUES (276,'Human Factors','Alcohol affects?','Reaction time','Car speed','Road','Tyres','A');
INSERT INTO questions VALUES (277,'Human Factors','Alcohol affects?','Reaction time','Car speed','Road','Tyres','A');
INSERT INTO questions VALUES (278,'Human Factors','Alcohol affects?','Reaction time','Car speed','Road','Tyres','A');
INSERT INTO questions VALUES (279,'Human Factors','Alcohol affects?','Reaction time','Car speed','Road','Tyres','A');
INSERT INTO questions VALUES (280,'Human Factors','Alcohol affects?','Reaction time','Car speed','Road','Tyres','A');
INSERT INTO questions VALUES (281,'Highway Code','Pedestrian at zebra crossing?','Priority','No priority','Ignore','Honk','A');
INSERT INTO questions VALUES (282,'Highway Code','Pedestrian at zebra crossing?','Priority','No priority','Ignore','Honk','A');
INSERT INTO questions VALUES (283,'Highway Code','Pedestrian at zebra crossing?','Priority','No priority','Ignore','Honk','A');
INSERT INTO questions VALUES (284,'Highway Code','Pedestrian at zebra crossing?','Priority','No priority','Ignore','Honk','A');
INSERT INTO questions VALUES (285,'Highway Code','Pedestrian at zebra crossing?','Priority','No priority','Ignore','Honk','A');
INSERT INTO questions VALUES (286,'Highway Code','Pedestrian at zebra crossing?','Priority','No priority','Ignore','Honk','A');
INSERT INTO questions VALUES (287,'Highway Code','Pedestrian at zebra crossing?','Priority','No priority','Ignore','Honk','A');
INSERT INTO questions VALUES (288,'Highway Code','Pedestrian at zebra crossing?','Priority','No priority','Ignore','Honk','A');
INSERT INTO questions VALUES (289,'Highway Code','Pedestrian at zebra crossing?','Priority','No priority','Ignore','Honk','A');
INSERT INTO questions VALUES (290,'Highway Code','Pedestrian at zebra crossing?','Priority','No priority','Ignore','Honk','A');
INSERT INTO questions VALUES (291,'Highway Code','Pedestrian at zebra crossing?','Priority','No priority','Ignore','Honk','A');
INSERT INTO questions VALUES (292,'Highway Code','Pedestrian at zebra crossing?','Priority','No priority','Ignore','Honk','A');
INSERT INTO questions VALUES (293,'Highway Code','Pedestrian at zebra crossing?','Priority','No priority','Ignore','Honk','A');
INSERT INTO questions VALUES (294,'Highway Code','Pedestrian at zebra crossing?','Priority','No priority','Ignore','Honk','A');
INSERT INTO questions VALUES (295,'Highway Code','Pedestrian at zebra crossing?','Priority','No priority','Ignore','Honk','A');
INSERT INTO questions VALUES (296,'Highway Code','Pedestrian at zebra crossing?','Priority','No priority','Ignore','Honk','A');
INSERT INTO questions VALUES (297,'Highway Code','Pedestrian at zebra crossing?','Priority','No priority','Ignore','Honk','A');
INSERT INTO questions VALUES (298,'Highway Code','Pedestrian at zebra crossing?','Priority','No priority','Ignore','Honk','A');
INSERT INTO questions VALUES (299,'Highway Code','Pedestrian at zebra crossing?','Priority','No priority','Ignore','Honk','A');
INSERT INTO questions VALUES (300,'Highway Code','Pedestrian at zebra crossing?','Priority','No priority','Ignore','Honk','A');
INSERT INTO questions VALUES (301,'Highway Code','Pedestrian at zebra crossing?','Priority','No priority','Ignore','Honk','A');
INSERT INTO questions VALUES (302,'Highway Code','Pedestrian at zebra crossing?','Priority','No priority','Ignore','Honk','A');
INSERT INTO questions VALUES (303,'Highway Code','Pedestrian at zebra crossing?','Priority','No priority','Ignore','Honk','A');
INSERT INTO questions VALUES (304,'Highway Code','Pedestrian at zebra crossing?','Priority','No priority','Ignore','Honk','A');
INSERT INTO questions VALUES (305,'Highway Code','Pedestrian at zebra crossing?','Priority','No priority','Ignore','Honk','A');
INSERT INTO questions VALUES (306,'Highway Code','Pedestrian at zebra crossing?','Priority','No priority','Ignore','Honk','A');
INSERT INTO questions VALUES (307,'Highway Code','Pedestrian at zebra crossing?','Priority','No priority','Ignore','Honk','A');
INSERT INTO questions VALUES (308,'Highway Code','Pedestrian at zebra crossing?','Priority','No priority','Ignore','Honk','A');
INSERT INTO questions VALUES (309,'Highway Code','Pedestrian at zebra crossing?','Priority','No priority','Ignore','Honk','A');
INSERT INTO questions VALUES (310,'Highway Code','Pedestrian at zebra crossing?','Priority','No priority','Ignore','Honk','A');
INSERT INTO questions VALUES (311,'Highway Code','Pedestrian at zebra crossing?','Priority','No priority','Ignore','Honk','A');
INSERT INTO questions VALUES (312,'Highway Code','Pedestrian at zebra crossing?','Priority','No priority','Ignore','Honk','A');
INSERT INTO questions VALUES (313,'Highway Code','Pedestrian at zebra crossing?','Priority','No priority','Ignore','Honk','A');
INSERT INTO questions VALUES (314,'Highway Code','Pedestrian at zebra crossing?','Priority','No priority','Ignore','Honk','A');
INSERT INTO questions VALUES (315,'Highway Code','Pedestrian at zebra crossing?','Priority','No priority','Ignore','Honk','A');
INSERT INTO questions VALUES (316,'Highway Code','Pedestrian at zebra crossing?','Priority','No priority','Ignore','Honk','A');
INSERT INTO questions VALUES (317,'Highway Code','Pedestrian at zebra crossing?','Priority','No priority','Ignore','Honk','A');
INSERT INTO questions VALUES (318,'Highway Code','Pedestrian at zebra crossing?','Priority','No priority','Ignore','Honk','A');
INSERT INTO questions VALUES (319,'Highway Code','Pedestrian at zebra crossing?','Priority','No priority','Ignore','Honk','A');
INSERT INTO questions VALUES (320,'Highway Code','Pedestrian at zebra crossing?','Priority','No priority','Ignore','Honk','A');
